import type { FastifyInstance } from 'fastify';
import { healthRoutes } from './health';
import { accountRoutes } from './accounts';
import { tokenRoutes } from './tokens';
import { transferRoutes } from './transfers';
import { payRoutes } from './pay';
import { bankLinkRoutes } from './bankLink';
import { fundRoutes } from './fund';
import { xrplRoutes } from './xrpl';
import { nftRoutes } from './nft';
import { onboardingRoutes } from './onboarding';
import { hcsRoutes } from './hcs';
import { fundingRoutes } from './funding';
import { rewardsRoutes } from './rewards';
import { credentialsIssueRoutes } from './credentialsIssue';
import { webhookRoutes } from './webhooks';
import { authRoutes } from './auth';
import { reconcileRoutes } from './reconcile';
import { redeemRoutes } from './redeem';
import { merchantRoutes } from './merchants';
import { stripeConnectRoutes } from './stripeConnect';
import { enrollmentRoutes } from './enrollment';
import { merchantRuleRoutes } from './merchantRules';

export async function registerRoutes(app: FastifyInstance) {
  app.register(healthRoutes);
  app.register(accountRoutes);
  app.register(tokenRoutes);
  app.register(transferRoutes);
  app.register(payRoutes);
  app.register(bankLinkRoutes);
  app.register(fundRoutes);
  app.register(xrplRoutes);
  app.register(nftRoutes);
  app.register(onboardingRoutes);
  app.register(hcsRoutes);
  app.register(fundingRoutes);
  app.register(rewardsRoutes);
  app.register(credentialsIssueRoutes);
  app.register(webhookRoutes);
  app.register(authRoutes);
  app.register(reconcileRoutes);
  app.register(redeemRoutes);
  app.register(merchantRoutes);
  app.register(stripeConnectRoutes);
  app.register(enrollmentRoutes);
  app.register(merchantRuleRoutes);
}
